import { PrismaClient, UserRole, FacilityType, InquiryStatus, InquiryActivityType } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const weekdaySet = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
const extendedWeekSet = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const fullWeekSet = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const weekendHeavySet = ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

const defaultFurniture = ['Consultation desk', 'Doctor chair', 'Patient chair', 'Storage cabinet'];
const pediatricFurniture = ['Child consultation desk', 'Family seating', 'Examination couch', 'Toy storage'];
const premiumFurniture = ['Executive consultation desk', 'Visitor sofa', 'Examination bed', 'Built-in storage'];
const diagnosticFurniture = ['Workstation counter', 'Procedure chair', 'Storage trolley', 'Waiting room seating'];

const dermatologyEquipment = ['Dermatoscope', 'Examination light', 'Pulse oximeter'];
const psychiatryEquipment = ['Acoustic privacy panels', 'Digital appointment terminal', 'Air purifier'];
const orthopedicEquipment = ['Examination bed', 'BP monitor', 'Digital weighing scale'];
const gastroEquipment = ['Examination couch', 'Vitals monitor', 'Infusion stand'];
const endocrineEquipment = ['Glucometer', 'Vitals monitor', 'Storage refrigerator'];
const pediatricEquipment = ['Infant weighing scale', 'Nebulizer', 'Pulse oximeter'];
const gynecologyEquipment = ['Examination couch', 'Procedure light', 'Privacy screen'];
const entEquipment = ['ENT chair', 'Headlight', 'Basic suction unit'];

function unsplashUrl(id: string, width = 1400) {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=80`;
}

const gallerySets = {
  premiumClinic: [
    unsplashUrl('photo-1576091160399-112ba8d25d1d'),
    unsplashUrl('photo-1586773860418-d37222d8fce3'),
    unsplashUrl('photo-1519494026892-80bbd2d6fd0d'),
  ],
  specialistWing: [
    unsplashUrl('photo-1666214280557-f1b5022eb634'),
    unsplashUrl('photo-1576091160550-2173dba999ef'),
    unsplashUrl('photo-1581056771107-24ca5f033842'),
  ],
  diagnosticsHub: [
    unsplashUrl('photo-1579154204601-01588f351e67'),
    unsplashUrl('photo-1599689868384-59cb2b01bb21'),
    unsplashUrl('photo-1580281657527-47f249e8f4df'),
  ],
  familyClinic: [
    unsplashUrl('photo-1538108149393-fbbd81895907'),
    unsplashUrl('photo-1516549655169-df83a0774514'),
    unsplashUrl('photo-1584515933487-779824d29309'),
  ],
  consultationFloor: [
    unsplashUrl('photo-1516549655169-df83a0774514'),
    unsplashUrl('photo-1579684385127-1ef15d508118'),
    unsplashUrl('photo-1505751172876-fa1923c5c528'),
  ],
  modernHospital: [
    unsplashUrl('photo-1530026405186-ed1f139313f8'),
    unsplashUrl('photo-1579154204601-01588f351e67'),
    unsplashUrl('photo-1515377905703-c4788e51af15'),
  ],
} as const;

type GalleryKey = keyof typeof gallerySets;

interface ListingSeed {
  id: string;
  clinicName: string;
  facilityType: FacilityType;
  city: string;
  locality: string;
  address: string;
  contactPerson: string;
  phone: string;
  email: string;
  whatsapp: string;
  roomsAvailable: number;
  roomSize: string;
  furniture: string[];
  equipment: string[];
  monthlyFee: number;
  slotFee?: number;
  deposit?: number;
  days: string[];
  hours: string;
  infrastructure: {
    parking: boolean;
    waitingArea: boolean;
    pharmacy: boolean;
    diagnostics: boolean;
    powerBackup: boolean;
  };
  specialties: string[];
  gallery: GalleryKey;
  verified: boolean;
  featured: boolean;
}

const listingsSeedData: ListingSeed[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    clinicName: 'LifeCare Multi-Specialty Clinic',
    facilityType: FacilityType.clinic,
    city: 'Hyderabad',
    locality: 'Kondapur',
    address: '3rd Floor, Cyber Towers Road, Kondapur, Hyderabad - 500084',
    contactPerson: 'Dr. Rajesh Kumar',
    phone: '+91 9876543210',
    email: 'admin@lifecareclinic.in',
    whatsapp: '+91 9876543210',
    roomsAvailable: 3,
    roomSize: '150 sq ft',
    furniture: premiumFurniture,
    equipment: [...dermatologyEquipment, 'Examination bed'],
    monthlyFee: 25000,
    slotFee: 500,
    deposit: 50000,
    days: extendedWeekSet,
    hours: '9:00 AM - 9:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['Dermatology', 'Endocrinology', 'Psychiatry'],
    gallery: 'premiumClinic',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    clinicName: 'Aster Family Consult Suites',
    facilityType: FacilityType.polyclinic,
    city: 'Hyderabad',
    locality: 'Banjara Hills',
    address: 'Road No. 12, Banjara Hills, Hyderabad - 500034',
    contactPerson: 'Dr. Mahati Reddy',
    phone: '+91 9876500002',
    email: 'operations@asterfamilysuites.in',
    whatsapp: '+91 9876500002',
    roomsAvailable: 4,
    roomSize: '170 sq ft',
    furniture: premiumFurniture,
    equipment: [...gynecologyEquipment, 'Vitals monitor'],
    monthlyFee: 42000,
    slotFee: 900,
    deposit: 85000,
    days: fullWeekSet,
    hours: '8:00 AM - 10:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['Gynecology', 'Pediatrics', 'ENT'],
    gallery: 'consultationFloor',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    clinicName: 'Cedar Ortho & Pain Clinic',
    facilityType: FacilityType.clinic,
    city: 'Hyderabad',
    locality: 'Gachibowli',
    address: 'Opp. Financial District Gate 2, Gachibowli, Hyderabad - 500032',
    contactPerson: 'Dr. S. Harish',
    phone: '+91 9876500003',
    email: 'hello@cedarortho.in',
    whatsapp: '+91 9876500003',
    roomsAvailable: 2,
    roomSize: '145 sq ft',
    furniture: defaultFurniture,
    equipment: [...orthopedicEquipment, 'Cold therapy unit'],
    monthlyFee: 28000,
    slotFee: 650,
    deposit: 40000,
    days: extendedWeekSet,
    hours: '10:00 AM - 8:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Orthopedics', 'Physiotherapy'],
    gallery: 'specialistWing',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    clinicName: 'Mindwell Behavioural Centre',
    facilityType: FacilityType.clinic,
    city: 'Hyderabad',
    locality: 'Jubilee Hills',
    address: 'Road No. 45, Jubilee Hills, Hyderabad - 500033',
    contactPerson: 'Dr. Aditi Varma',
    phone: '+91 9876500004',
    email: 'support@mindwellcentre.in',
    whatsapp: '+91 9876500004',
    roomsAvailable: 3,
    roomSize: '130 sq ft',
    furniture: ['Therapy desk', 'Lounge seating', 'Storage console', 'Accent lighting'],
    equipment: psychiatryEquipment,
    monthlyFee: 23000,
    slotFee: 550,
    deposit: 35000,
    days: weekendHeavySet,
    hours: '11:00 AM - 8:00 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Psychiatry', 'Clinical Psychology'],
    gallery: 'familyClinic',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    clinicName: 'Apollo Diagnostics Annex',
    facilityType: FacilityType.diagnostic_center,
    city: 'Hyderabad',
    locality: 'Himayatnagar',
    address: 'Street 6, Himayatnagar Main Road, Hyderabad - 500029',
    contactPerson: 'Dr. Neeraj Suri',
    phone: '+91 9876500005',
    email: 'ops@apollodiagnosticsannex.in',
    whatsapp: '+91 9876500005',
    roomsAvailable: 5,
    roomSize: '190 sq ft',
    furniture: diagnosticFurniture,
    equipment: ['Procedure chair', 'ECG unit', 'Ultrasound access point'],
    monthlyFee: 36000,
    slotFee: 800,
    deposit: 70000,
    days: fullWeekSet,
    hours: '7:00 AM - 9:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['Gastroenterology', 'Endocrinology', 'General Medicine'],
    gallery: 'diagnosticsHub',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    clinicName: 'Avenue Children’s Consult Rooms',
    facilityType: FacilityType.clinic,
    city: 'Bangalore',
    locality: 'Indiranagar',
    address: '12th Main, HAL 2nd Stage, Indiranagar, Bangalore - 560038',
    contactPerson: 'Dr. Meghana Joshi',
    phone: '+91 9876500006',
    email: 'care@avenuechildrensuites.in',
    whatsapp: '+91 9876500006',
    roomsAvailable: 3,
    roomSize: '155 sq ft',
    furniture: pediatricFurniture,
    equipment: [...pediatricEquipment, 'Vaccination refrigerator'],
    monthlyFee: 30000,
    slotFee: 700,
    deposit: 45000,
    days: extendedWeekSet,
    hours: '9:00 AM - 8:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: false, powerBackup: true },
    specialties: ['Pediatrics', 'ENT'],
    gallery: 'familyClinic',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    clinicName: 'Koramangala Women’s Health Hub',
    facilityType: FacilityType.polyclinic,
    city: 'Bangalore',
    locality: 'Koramangala',
    address: '80 Feet Road, Koramangala 4th Block, Bangalore - 560034',
    contactPerson: 'Dr. Nandita Rao',
    phone: '+91 9876500007',
    email: 'desk@womenshealthhub.in',
    whatsapp: '+91 9876500007',
    roomsAvailable: 4,
    roomSize: '165 sq ft',
    furniture: premiumFurniture,
    equipment: [...gynecologyEquipment, 'Fetal Doppler'],
    monthlyFee: 41000,
    slotFee: 950,
    deposit: 78000,
    days: fullWeekSet,
    hours: '8:30 AM - 9:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['Gynecology', 'Endocrinology'],
    gallery: 'premiumClinic',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    clinicName: 'Whitefield Specialty Chambers',
    facilityType: FacilityType.hospital,
    city: 'Bangalore',
    locality: 'Whitefield',
    address: 'ITPL Main Road, Whitefield, Bangalore - 560066',
    contactPerson: 'Dr. Rohan Bhave',
    phone: '+91 9876500008',
    email: 'leasing@whitefieldspecialty.in',
    whatsapp: '+91 9876500008',
    roomsAvailable: 6,
    roomSize: '185 sq ft',
    furniture: premiumFurniture,
    equipment: [...gastroEquipment, 'Procedure light'],
    monthlyFee: 47000,
    slotFee: 1100,
    deposit: 90000,
    days: extendedWeekSet,
    hours: '8:00 AM - 10:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['Gastroenterology', 'ENT', 'General Medicine'],
    gallery: 'modernHospital',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000009',
    clinicName: 'Jayanagar Endocrine Studio',
    facilityType: FacilityType.clinic,
    city: 'Bangalore',
    locality: 'Jayanagar',
    address: '11th Main, Jayanagar 3rd Block, Bangalore - 560011',
    contactPerson: 'Dr. Aparna Nair',
    phone: '+91 9876500009',
    email: 'hello@endocrinestudio.in',
    whatsapp: '+91 9876500009',
    roomsAvailable: 2,
    roomSize: '135 sq ft',
    furniture: defaultFurniture,
    equipment: [...endocrineEquipment, 'Body composition analyser'],
    monthlyFee: 26500,
    slotFee: 600,
    deposit: 38000,
    days: weekdaySet,
    hours: '9:30 AM - 7:30 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Endocrinology', 'Nutrition'],
    gallery: 'consultationFloor',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000010',
    clinicName: 'Marina Coast ENT & Allergy Centre',
    facilityType: FacilityType.clinic,
    city: 'Chennai',
    locality: 'Adyar',
    address: 'LB Road, Adyar, Chennai - 600020',
    contactPerson: 'Dr. Vishal Krishnan',
    phone: '+91 9876500010',
    email: 'admin@marinacoastent.in',
    whatsapp: '+91 9876500010',
    roomsAvailable: 2,
    roomSize: '145 sq ft',
    furniture: defaultFurniture,
    equipment: [...entEquipment, 'Audiometry workstation'],
    monthlyFee: 25500,
    slotFee: 580,
    deposit: 36000,
    days: extendedWeekSet,
    hours: '10:00 AM - 8:00 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['ENT', 'Pulmonology'],
    gallery: 'specialistWing',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000011',
    clinicName: 'Anna Nagar Child & Family Clinic',
    facilityType: FacilityType.polyclinic,
    city: 'Chennai',
    locality: 'Anna Nagar',
    address: '2nd Avenue, Anna Nagar, Chennai - 600040',
    contactPerson: 'Dr. Priyanka Srinivasan',
    phone: '+91 9876500011',
    email: 'ops@annanagarfamilyclinic.in',
    whatsapp: '+91 9876500011',
    roomsAvailable: 3,
    roomSize: '160 sq ft',
    furniture: pediatricFurniture,
    equipment: [...pediatricEquipment, 'Procedure trolley'],
    monthlyFee: 29500,
    slotFee: 650,
    deposit: 42000,
    days: fullWeekSet,
    hours: '8:30 AM - 8:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: false, powerBackup: true },
    specialties: ['Pediatrics', 'General Medicine'],
    gallery: 'familyClinic',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000012',
    clinicName: 'Velachery Women & Wellness Chambers',
    facilityType: FacilityType.hospital,
    city: 'Chennai',
    locality: 'Velachery',
    address: '100 Feet Bypass Road, Velachery, Chennai - 600042',
    contactPerson: 'Dr. Keerthana Iyer',
    phone: '+91 9876500012',
    email: 'leasing@velacherywellness.in',
    whatsapp: '+91 9876500012',
    roomsAvailable: 5,
    roomSize: '180 sq ft',
    furniture: premiumFurniture,
    equipment: [...gynecologyEquipment, 'Ultrasound access point'],
    monthlyFee: 39000,
    slotFee: 900,
    deposit: 76000,
    days: fullWeekSet,
    hours: '8:00 AM - 9:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['Gynecology', 'Pediatrics'],
    gallery: 'modernHospital',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000013',
    clinicName: 'Nungambakkam Skin & Hair Studio',
    facilityType: FacilityType.clinic,
    city: 'Chennai',
    locality: 'Nungambakkam',
    address: 'Khader Nawaz Khan Road, Nungambakkam, Chennai - 600034',
    contactPerson: 'Dr. R. Lavanya',
    phone: '+91 9876500013',
    email: 'bookings@skinandhairstudio.in',
    whatsapp: '+91 9876500013',
    roomsAvailable: 2,
    roomSize: '125 sq ft',
    furniture: defaultFurniture,
    equipment: [...dermatologyEquipment, 'Procedure stool'],
    monthlyFee: 27000,
    slotFee: 620,
    deposit: 32000,
    days: weekdaySet,
    hours: '10:30 AM - 7:30 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Dermatology', 'Cosmetology'],
    gallery: 'premiumClinic',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000014',
    clinicName: 'Powai Digestive Care Suites',
    facilityType: FacilityType.hospital,
    city: 'Mumbai',
    locality: 'Powai',
    address: 'Hiranandani Gardens, Powai, Mumbai - 400076',
    contactPerson: 'Dr. Kunal Deshpande',
    phone: '+91 9876500014',
    email: 'operations@digestivecaresuites.in',
    whatsapp: '+91 9876500014',
    roomsAvailable: 4,
    roomSize: '175 sq ft',
    furniture: premiumFurniture,
    equipment: [...gastroEquipment, 'Recovery recliner'],
    monthlyFee: 52000,
    slotFee: 1200,
    deposit: 95000,
    days: extendedWeekSet,
    hours: '8:00 AM - 9:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['Gastroenterology', 'General Medicine'],
    gallery: 'modernHospital',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000015',
    clinicName: 'Andheri West Ortho Rooms',
    facilityType: FacilityType.clinic,
    city: 'Mumbai',
    locality: 'Andheri West',
    address: 'Lokhandwala Market Road, Andheri West, Mumbai - 400053',
    contactPerson: 'Dr. Mihir Shah',
    phone: '+91 9876500015',
    email: 'care@andheriortho.in',
    whatsapp: '+91 9876500015',
    roomsAvailable: 3,
    roomSize: '150 sq ft',
    furniture: defaultFurniture,
    equipment: [...orthopedicEquipment, 'Portable ultrasound'],
    monthlyFee: 36000,
    slotFee: 850,
    deposit: 54000,
    days: extendedWeekSet,
    hours: '9:30 AM - 8:30 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Orthopedics', 'Sports Medicine'],
    gallery: 'specialistWing',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000016',
    clinicName: 'Bandra Women’s Day Care Clinic',
    facilityType: FacilityType.polyclinic,
    city: 'Mumbai',
    locality: 'Bandra West',
    address: 'Hill Road, Bandra West, Mumbai - 400050',
    contactPerson: 'Dr. Sanjana Mehta',
    phone: '+91 9876500016',
    email: 'support@bandrawomenscare.in',
    whatsapp: '+91 9876500016',
    roomsAvailable: 4,
    roomSize: '170 sq ft',
    furniture: premiumFurniture,
    equipment: [...gynecologyEquipment, 'Vitals monitor'],
    monthlyFee: 48500,
    slotFee: 1100,
    deposit: 82000,
    days: fullWeekSet,
    hours: '8:00 AM - 10:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['Gynecology', 'Pediatrics'],
    gallery: 'consultationFloor',
    verified: true,
    featured: true,
  },
  {
    id: '00000000-0000-0000-0000-000000000017',
    clinicName: 'Dadar Endocrine & Metabolic Centre',
    facilityType: FacilityType.clinic,
    city: 'Mumbai',
    locality: 'Dadar West',
    address: 'Senapati Bapat Marg, Dadar West, Mumbai - 400028',
    contactPerson: 'Dr. Akanksha Bhosale',
    phone: '+91 9876500017',
    email: 'desk@metaboliccentre.in',
    whatsapp: '+91 9876500017',
    roomsAvailable: 2,
    roomSize: '135 sq ft',
    furniture: defaultFurniture,
    equipment: [...endocrineEquipment, 'Point-of-care testing station'],
    monthlyFee: 31500,
    slotFee: 700,
    deposit: 42000,
    days: weekdaySet,
    hours: '9:00 AM - 7:00 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Endocrinology', 'Nutrition'],
    gallery: 'familyClinic',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000018',
    clinicName: 'Baner Child Development Suites',
    facilityType: FacilityType.clinic,
    city: 'Pune',
    locality: 'Baner',
    address: 'Baner Road, Baner, Pune - 411045',
    contactPerson: 'Dr. Shruti Kulkarni',
    phone: '+91 9876500018',
    email: 'booking@childdevelopmentsuites.in',
    whatsapp: '+91 9876500018',
    roomsAvailable: 3,
    roomSize: '150 sq ft',
    furniture: pediatricFurniture,
    equipment: [...pediatricEquipment, 'Hearing screening kit'],
    monthlyFee: 26000,
    slotFee: 600,
    deposit: 35000,
    days: extendedWeekSet,
    hours: '9:00 AM - 8:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Pediatrics', 'ENT'],
    gallery: 'familyClinic',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000019',
    clinicName: 'Kothrud Skin & Wellness Rooms',
    facilityType: FacilityType.clinic,
    city: 'Pune',
    locality: 'Kothrud',
    address: 'Paud Road, Kothrud, Pune - 411038',
    contactPerson: 'Dr. Revati Patwardhan',
    phone: '+91 9876500019',
    email: 'admin@skinwellnessrooms.in',
    whatsapp: '+91 9876500019',
    roomsAvailable: 2,
    roomSize: '128 sq ft',
    furniture: defaultFurniture,
    equipment: [...dermatologyEquipment, 'Laser preparation trolley'],
    monthlyFee: 22500,
    slotFee: 500,
    deposit: 30000,
    days: weekdaySet,
    hours: '10:00 AM - 7:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: false },
    specialties: ['Dermatology', 'Cosmetology'],
    gallery: 'premiumClinic',
    verified: false,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000020',
    clinicName: 'Viman Nagar Consultation Arcade',
    facilityType: FacilityType.polyclinic,
    city: 'Pune',
    locality: 'Viman Nagar',
    address: 'Town Square Road, Viman Nagar, Pune - 411014',
    contactPerson: 'Dr. Shashank Apte',
    phone: '+91 9876500020',
    email: 'ops@consultationarcade.in',
    whatsapp: '+91 9876500020',
    roomsAvailable: 4,
    roomSize: '165 sq ft',
    furniture: premiumFurniture,
    equipment: [...gastroEquipment, ...entEquipment],
    monthlyFee: 34500,
    slotFee: 780,
    deposit: 52000,
    days: fullWeekSet,
    hours: '8:30 AM - 9:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['ENT', 'Gastroenterology', 'General Medicine'],
    gallery: 'consultationFloor',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000021',
    clinicName: 'Wakad Women & Endocrine Chambers',
    facilityType: FacilityType.clinic,
    city: 'Pune',
    locality: 'Wakad',
    address: 'Datta Mandir Road, Wakad, Pune - 411057',
    contactPerson: 'Dr. Ishita Gokhale',
    phone: '+91 9876500021',
    email: 'frontdesk@wakadwellness.in',
    whatsapp: '+91 9876500021',
    roomsAvailable: 3,
    roomSize: '148 sq ft',
    furniture: premiumFurniture,
    equipment: [...gynecologyEquipment, ...endocrineEquipment],
    monthlyFee: 28500,
    slotFee: 650,
    deposit: 36000,
    days: extendedWeekSet,
    hours: '9:00 AM - 8:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Gynecology', 'Endocrinology'],
    gallery: 'specialistWing',
    verified: false,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000022',
    clinicName: 'GK Digestive & Liver Clinic',
    facilityType: FacilityType.clinic,
    city: 'Delhi',
    locality: 'Greater Kailash II',
    address: 'M Block Market, Greater Kailash II, New Delhi - 110048',
    contactPerson: 'Dr. Aviral Bhatia',
    phone: '+91 9876500022',
    email: 'connect@gkdigestive.in',
    whatsapp: '+91 9876500022',
    roomsAvailable: 3,
    roomSize: '155 sq ft',
    furniture: defaultFurniture,
    equipment: [...gastroEquipment, 'Vitals monitor'],
    monthlyFee: 38000,
    slotFee: 850,
    deposit: 60000,
    days: extendedWeekSet,
    hours: '9:00 AM - 8:30 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['Gastroenterology', 'General Medicine'],
    gallery: 'specialistWing',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000023',
    clinicName: 'South Ex Skin & Hormone Studio',
    facilityType: FacilityType.clinic,
    city: 'Delhi',
    locality: 'South Extension',
    address: 'South Extension Part II, New Delhi - 110049',
    contactPerson: 'Dr. Meera Taneja',
    phone: '+91 9876500023',
    email: 'hello@south-exstudio.in',
    whatsapp: '+91 9876500023',
    roomsAvailable: 2,
    roomSize: '132 sq ft',
    furniture: defaultFurniture,
    equipment: [...dermatologyEquipment, ...endocrineEquipment],
    monthlyFee: 33500,
    slotFee: 780,
    deposit: 48000,
    days: weekdaySet,
    hours: '10:00 AM - 7:00 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Dermatology', 'Endocrinology'],
    gallery: 'premiumClinic',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000024',
    clinicName: 'Dwarka Family Consult Hub',
    facilityType: FacilityType.polyclinic,
    city: 'Delhi',
    locality: 'Dwarka Sector 12',
    address: 'Sector 12 Market, Dwarka, New Delhi - 110078',
    contactPerson: 'Dr. Sunil Kaushik',
    phone: '+91 9876500024',
    email: 'ops@dwarkafamilyhub.in',
    whatsapp: '+91 9876500024',
    roomsAvailable: 4,
    roomSize: '162 sq ft',
    furniture: premiumFurniture,
    equipment: [...pediatricEquipment, ...entEquipment],
    monthlyFee: 32000,
    slotFee: 700,
    deposit: 45000,
    days: fullWeekSet,
    hours: '8:30 AM - 9:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: false, powerBackup: true },
    specialties: ['Pediatrics', 'ENT', 'General Medicine'],
    gallery: 'consultationFloor',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000025',
    clinicName: 'Rohini Ortho & Rehab Bay',
    facilityType: FacilityType.hospital,
    city: 'Delhi',
    locality: 'Rohini Sector 9',
    address: 'Sector 9 Institutional Area, Rohini, Delhi - 110085',
    contactPerson: 'Dr. Naveen Malik',
    phone: '+91 9876500025',
    email: 'leasing@orthorehabbay.in',
    whatsapp: '+91 9876500025',
    roomsAvailable: 5,
    roomSize: '185 sq ft',
    furniture: premiumFurniture,
    equipment: [...orthopedicEquipment, 'Rehab bench'],
    monthlyFee: 36500,
    slotFee: 820,
    deposit: 52000,
    days: extendedWeekSet,
    hours: '8:00 AM - 9:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['Orthopedics', 'Sports Medicine'],
    gallery: 'modernHospital',
    verified: false,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000026',
    clinicName: 'Krishna River ENT Rooms',
    facilityType: FacilityType.clinic,
    city: 'Vijayawada',
    locality: 'Benz Circle',
    address: 'MG Road, Benz Circle, Vijayawada - 520010',
    contactPerson: 'Dr. K. Pranathi',
    phone: '+91 9876500026',
    email: 'desk@krishnariverent.in',
    whatsapp: '+91 9876500026',
    roomsAvailable: 2,
    roomSize: '138 sq ft',
    furniture: defaultFurniture,
    equipment: [...entEquipment, 'Nebulizer'],
    monthlyFee: 21000,
    slotFee: 450,
    deposit: 25000,
    days: extendedWeekSet,
    hours: '9:30 AM - 7:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['ENT', 'Pediatrics'],
    gallery: 'familyClinic',
    verified: false,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000027',
    clinicName: 'Governorpet General Consult Centre',
    facilityType: FacilityType.polyclinic,
    city: 'Vijayawada',
    locality: 'Governorpet',
    address: 'Eluru Road, Governorpet, Vijayawada - 520002',
    contactPerson: 'Dr. P. Lokesh',
    phone: '+91 9876500027',
    email: 'admin@governorpetconsult.in',
    whatsapp: '+91 9876500027',
    roomsAvailable: 3,
    roomSize: '150 sq ft',
    furniture: defaultFurniture,
    equipment: ['Vitals monitor', 'Nebulizer', 'Portable ECG'],
    monthlyFee: 24000,
    slotFee: 500,
    deposit: 30000,
    days: fullWeekSet,
    hours: '8:00 AM - 8:00 PM',
    infrastructure: { parking: false, waitingArea: true, pharmacy: true, diagnostics: false, powerBackup: true },
    specialties: ['General Medicine', 'Endocrinology'],
    gallery: 'consultationFloor',
    verified: false,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000028',
    clinicName: 'Bayview Pediatric & Women Care',
    facilityType: FacilityType.hospital,
    city: 'Vizag',
    locality: 'MVP Colony',
    address: 'Sector 5, MVP Colony, Visakhapatnam - 530017',
    contactPerson: 'Dr. Saipriya Murthy',
    phone: '+91 9876500028',
    email: 'care@bayviewcare.in',
    whatsapp: '+91 9876500028',
    roomsAvailable: 4,
    roomSize: '170 sq ft',
    furniture: pediatricFurniture,
    equipment: [...pediatricEquipment, ...gynecologyEquipment],
    monthlyFee: 28500,
    slotFee: 620,
    deposit: 35000,
    days: fullWeekSet,
    hours: '8:30 AM - 9:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: true, diagnostics: true, powerBackup: true },
    specialties: ['Pediatrics', 'Gynecology'],
    gallery: 'modernHospital',
    verified: true,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000029',
    clinicName: 'Siripuram Skin & Cosmetology Suites',
    facilityType: FacilityType.clinic,
    city: 'Vizag',
    locality: 'Siripuram',
    address: 'VIP Road, Siripuram, Visakhapatnam - 530003',
    contactPerson: 'Dr. Deeksha Ganta',
    phone: '+91 9876500029',
    email: 'book@siripuramskin.in',
    whatsapp: '+91 9876500029',
    roomsAvailable: 2,
    roomSize: '132 sq ft',
    furniture: defaultFurniture,
    equipment: [...dermatologyEquipment, 'Dermapen station'],
    monthlyFee: 23000,
    slotFee: 520,
    deposit: 28000,
    days: weekdaySet,
    hours: '10:00 AM - 7:00 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: false, powerBackup: true },
    specialties: ['Dermatology', 'Cosmetology'],
    gallery: 'premiumClinic',
    verified: false,
    featured: false,
  },
  {
    id: '00000000-0000-0000-0000-000000000030',
    clinicName: 'Dwaraka Nagar Multi-Specialty Arcade',
    facilityType: FacilityType.diagnostic_center,
    city: 'Vizag',
    locality: 'Dwaraka Nagar',
    address: 'RTC Complex Road, Dwaraka Nagar, Visakhapatnam - 530016',
    contactPerson: 'Dr. Aditya Kumar',
    phone: '+91 9876500030',
    email: 'ops@dwarakanagararcade.in',
    whatsapp: '+91 9876500030',
    roomsAvailable: 5,
    roomSize: '185 sq ft',
    furniture: diagnosticFurniture,
    equipment: ['Portable ultrasound', 'Vitals monitor', 'ECG unit', 'Procedure chair'],
    monthlyFee: 32000,
    slotFee: 760,
    deposit: 42000,
    days: extendedWeekSet,
    hours: '8:00 AM - 8:30 PM',
    infrastructure: { parking: true, waitingArea: true, pharmacy: false, diagnostics: true, powerBackup: true },
    specialties: ['Gastroenterology', 'Orthopedics', 'ENT'],
    gallery: 'diagnosticsHub',
    verified: true,
    featured: false,
  },
];

function buildListingPayload(seed: ListingSeed, ownerUserId: string) {
  return {
    clinicName: seed.clinicName,
    facilityType: seed.facilityType,
    city: seed.city,
    locality: seed.locality,
    address: seed.address,
    contactPerson: seed.contactPerson,
    phone: seed.phone,
    email: seed.email,
    whatsapp: seed.whatsapp,
    rooms: {
      available: seed.roomsAvailable,
      size: seed.roomSize,
      furniture: seed.furniture,
      equipment: seed.equipment,
    },
    pricing: {
      monthlyFee: seed.monthlyFee,
      slotFee: seed.slotFee,
      deposit: seed.deposit,
    },
    availability: {
      days: seed.days,
      hours: seed.hours,
    },
    infrastructure: seed.infrastructure,
    specialties: seed.specialties,
    images: [...gallerySets[seed.gallery]],
    verified: seed.verified,
    featured: seed.featured,
    ownerUserId,
  };
}

async function seedUsers() {
  const adminPass = 'MedAdmin@2024!';
  const doctorPass = 'Doctor@2024!';
  const clinicPass = 'Clinic@2024!';

  const adminHash = await bcrypt.hash(adminPass, 10);
  const doctorHash = await bcrypt.hash(doctorPass, 10);
  const clinicHash = await bcrypt.hash(clinicPass, 10);

  await prisma.user.upsert({
    where: { email: 'admin@medspaces.in' },
    update: {},
    create: {
      name: 'MedSpaces Admin',
      email: 'admin@medspaces.in',
      passwordHash: adminHash,
      role: UserRole.ADMIN,
    },
  });

  await prisma.user.upsert({
    where: { email: 'doctor@medspaces.in' },
    update: {},
    create: {
      name: 'Dr. Sneha Patel',
      email: 'doctor@medspaces.in',
      passwordHash: doctorHash,
      role: UserRole.DOCTOR,
    },
  });

  await prisma.user.upsert({
    where: { email: 'clinic@medspaces.in' },
    update: {},
    create: {
      name: 'LifeCare Clinic Admin',
      email: 'clinic@medspaces.in',
      passwordHash: clinicHash,
      role: UserRole.CLINIC_OWNER,
    },
  });
}

async function main() {
  console.log('Seeding database...');

  await seedUsers();

  const clinicUser = await prisma.user.findUniqueOrThrow({
    where: { email: 'clinic@medspaces.in' },
  });

  const doctorUser = await prisma.user.findUniqueOrThrow({
    where: { email: 'doctor@medspaces.in' },
  });

  for (const listing of listingsSeedData) {
    await prisma.listing.upsert({
      where: { id: listing.id },
      update: buildListingPayload(listing, clinicUser.id),
      create: {
        id: listing.id,
        ...buildListingPayload(listing, clinicUser.id),
      },
    });
  }

  await prisma.doctor.upsert({
    where: { email: 'doctor.sneha@medspaces.in' },
    update: {},
    create: {
      fullName: 'Dr. Sneha Patel',
      email: 'doctor.sneha@medspaces.in',
      phone: '+91 9000000001',
      specialty: 'Dermatology',
      experience: 8,
      qualification: 'MBBS, MD Dermatology',
    },
  });

  await prisma.inquiry.upsert({
    where: { id: '00000000-0000-0000-0000-000000000011' },
    update: {
      status: InquiryStatus.NEW,
      createdByUserId: doctorUser.id,
      listingId: '00000000-0000-0000-0000-000000000001',
    },
    create: {
      id: '00000000-0000-0000-0000-000000000011',
      listingId: '00000000-0000-0000-0000-000000000001',
      createdByUserId: doctorUser.id,
      doctorName: 'Dr. Sneha Patel',
      specialty: 'Dermatology',
      email: 'doctor@medspaces.in',
      phone: '+91 9999999999',
      message: 'I would like to enquire about clinic availability.',
      status: InquiryStatus.NEW,
    },
  });

  await prisma.inquiryActivity.upsert({
    where: { id: '00000000-0000-0000-0000-000000000021' },
    update: {
      actorUserId: doctorUser.id,
      inquiryId: '00000000-0000-0000-0000-000000000011',
      type: InquiryActivityType.INQUIRY_CREATED,
      title: 'Inquiry submitted',
      description: 'The doctor submitted the initial inquiry.',
      toStatus: InquiryStatus.NEW,
    },
    create: {
      id: '00000000-0000-0000-0000-000000000021',
      inquiryId: '00000000-0000-0000-0000-000000000011',
      actorUserId: doctorUser.id,
      type: InquiryActivityType.INQUIRY_CREATED,
      title: 'Inquiry submitted',
      description: 'The doctor submitted the initial inquiry.',
      toStatus: InquiryStatus.NEW,
    },
  });

  console.log(`Seeded ${listingsSeedData.length} marketplace listings.`);
  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
